#!/usr/bin/env bash

set -e
set -o pipefail
set -x

for file in ./tests/*.test; do
  if ! (cat "$file" | nix-build-for-each 'echo ' | diff -q $file.expected -); then
    cat "$file" | nix-build-for-each 'echo ' | diff $file.expected -
    echo "Test failed: $file"
    exit 1
  fi
done

echo "Success!"
